branches:
  except:
    - master

skip_tags: true

environment:

  matrix:

    - PYTHON: "C:\\Python27"
      TOX_ENV: test-py27

    - PYTHON: "C:\\Python36"
      TOX_ENV: test-py36

build: off

install:
  - cmd: "%PYTHON%\\Scripts\\pip.exe install tox==3.0.0"

test_script:
  - cmd: "%PYTHON%\\Scripts\\tox.exe -e %TOX_ENV%"
  - cmd: "%PYTHON%\\Scripts\\tox.exe -e release"
