branches:
  except:
    - master

skip_tags: true

environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"

build: off

install:
  - cmd: "%PYTHON%\\Scripts\\pip.exe install tox==3.0.0"

test_script:

  - cmd: "%PYTHON%\\Scripts\\tox.exe -e lint-py27"
  - cmd: "%PYTHON%\\Scripts\\tox.exe -e test-py27"

  # For some reason codecov fails looking up coverage reports.
  # So we move the report to the standard path.
  - cmd: "copy reports\\coverage\\coverage.xml coverage.xml"

  - cmd: "%PYTHON%\\Scripts\\tox.exe -e codecov"
  - cmd: "%PYTHON%\\Scripts\\tox.exe -e release"
