environment:

  matrix:

    - PYTHON: "C:\\Python27"
      TOX_ENV: py27

    - PYTHON: "C:\\Python36"
      TOX_ENV: py36

build: off

cache:
  - .tox

install:
  - cmd: "%PYTHON%\\Scripts\\pip.exe install tox==3.0.0"

test_script:
  - cmd: "%PYTHON%\\Scripts\\tox.exe -e %TOX_ENV%"
