sudo: false

os: osx
language: generic
osx_image: xcode7.3

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: test-py27
      env:
        - PYTHON=2.7.14
        - PYENV_VERSION=2.7.14
    - stage: test
      name: test-py36
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
    - stage: test
      name: test-cross-distro
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
    - stage: release
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      name: release


branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

cache:
  directories:
    - ${HOME}/.pyenv_cache
    - ${TRAVIS_BUILD_DIR}/.tox

install:
  - pip install tox==3.0.0

script:
  - tox -e ${TRAVIS_JOB_NAME}

before_install: |

  source setup-pyenv.sh
