sudo: false

stages:
  - integration
  - release

env:
  global:
    - TOX_VERSION=3.0.0
    - CACHE_NAME=${TRAVIS_JOB_NAME}

jobs:
  include:

    - stage: integration
      name: py27-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=2.7.14
        - PYENV_VERSION=2.7.14
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e lint && tox -e test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f reports/coverage/coverage.xml
      cache:
        directories:
          - ${HOME}/.pyenv_cache
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py36-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e lint && tox -e test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f reports/coverage/coverage.xml
      cache:
        directories:
          - ${HOME}/.pyenv_cache
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py27-linux
      language: python
      python: "2.7"
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e lint && tox -e test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f reports/coverage/coverage.xml
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py36-linux
      language: python
      python: "3.6"
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e lint && tox -e test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f reports/coverage/coverage.xml
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: binary-cross-distro-linux
      language: python
      python: "3.6"
      services:
        - docker
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e test-cross-distro
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py27-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install: choco install python2
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e lint && tox -e test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f reports/coverage/coverage.xml
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox
          - /c/Python27

    - stage: integration
      name: py36-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install: choco install python --version 3.6.7
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e lint && tox -e test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f reports/coverage/coverage.xml
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox
          - /c/Python36

    - stage: release
      name: macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e release
      cache:
        directories:
          - ${HOME}/.pyenv_cache
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: release
      name: linux
      language: python
      python: "3.6"
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e release
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: release
      name: windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install: choco install python --version 3.6.7
      install:
        - pip install tox==${TOX_VERSION}
      script:
        - tox -e release
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox
          - /c/Python36

branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

