sudo: false

stages:
  - integration
  - release

env:
  global:
    - CACHE_NAME=${TRAVIS_JOB_NAME}

_commands_provider:

  _test_unit: &_test_unit make test-unit

  _test_cross_distro: &_test_cross_distro make test-cross-distro

  _lint: &_lint make lint

  _release: &_release make release

  _codecov: &_codecov make codecov

  _install_test_requirements: &_install_test_requirements make dep-test

  _install_requirements: &_install_requirements make dep-project

  # https://ttcshelbyville.wordpress.com/2012/12/19/disable-remote-differential-compression-form-the-command-line/
  _disable_windows_compression: &_disable_windows_compression "powershell Disable-WindowsOptionalFeature -Online -FeatureName MSRDC-Infrastructure"

  # https://travis-ci.community/t/yarn-network-troubles/333/7
  _disable_windows_defender: &_disable_windows_defender "powershell Set-MpPreference -DisableRealtimeMonitoring \\$true"


_steps_provider:

  _test_unit: &_step_test_unit

    install:
      - *_install_test_requirements
      - *_install_requirements
    before_script: *_lint
    script: *_test_unit
    after_success: *_codecov

  _test_cross_distro: &_step_test_cross_distro

    install:
      - *_install_test_requirements
      - *_install_requirements
    script: *_test_cross_distro
    after_success: *_codecov

  _release: &_step_release

    install: *_install_requirements
    script: *_release


jobs:
  include:

    - stage: integration
      name: py27-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=2.7.14
      before_install: source scripts/setup-pyenv.sh
      <<: *_step_test_unit
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py36-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.6.4
      before_install: source scripts/setup-pyenv.sh
      <<: *_step_test_unit
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py27-linux
      language: python
      python: "2.7"
      <<: *_step_test_unit

    - stage: integration
      name: py36-linux
      language: python
      python: "3.6"
      <<: *_step_test_unit

    - stage: integration
      name: binary-cross-distro-linux
      language: python
      python: "3.6"
      services:
        - docker
      <<: *_step_test_cross_distro

    - stage: integration
      name: py27-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install:
        - *_disable_windows_compression
        - *_disable_windows_defender
        - choco install make
        - choco install python2
      <<: *_step_test_unit

    - stage: integration
      name: py36-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        - *_disable_windows_compression
        - *_disable_windows_defender
        - choco install make
        - choco install python --version 3.6.7
      <<: *_step_test_unit

    - stage: release
      name: macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.6.4
      before_install: source scripts/setup-pyenv.sh
      <<: *_step_release
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: release
      name: linux
      language: python
      python: "3.6"
      <<: *_step_release

    - stage: release
      name: windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        - *_disable_windows_compression
        - *_disable_windows_defender
        - choco install make
        - choco install python --version 3.6.7
      <<: *_step_release

branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

