sudo: false

stages:
  - integration
  - release


jobs:
  include:

    - stage: integration
      name: py27-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=2.7.14
        - PYENV_VERSION=2.7.14
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==3.0.0
        - tox --notest -e lint -e test -e codecov
      script:
        - tox -e lint -e test -e codecov
      cache:
        directories:
          - ${HOME}/.pyenv_cache
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py36-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==3.0.0
        - tox --notest -e lint -e test -e codecov
      script:
        - tox -e lint -e test -e codecov
      cache:
        directories:
          - ${HOME}/.pyenv_cache
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py27-linux
      language: python
      python: "2.7"
      env:
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      install:
        - pip install tox==3.0.0
        - tox --notest -e lint -e test -e codecov
      script:
        - tox -e lint -e test -e codecov
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py36-linux
      language: python
      python: "3.6"
      env:
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      install:
        - pip install tox==3.0.0
        - tox --notest -e lint -e test -e codecov
      script:
        - tox -e lint -e test -e codecov
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: integration
      name: py27-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      before_install: choco install python2
      install:
        - pip install tox==3.0.0
        - tox --notest -e lint -e test -e codecov
      script:
        - tox -e lint -e test -e codecov
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox
          - /c/Python27
          - ${TRAVIS_BUILD_DIR}/REAMDE.md

    - stage: integration
      name: py36-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      before_install: choco install python --version 3.6.7
      install:
        - pip install tox==3.0.0
        - tox --notest -e lint -e test -e codecov
      script:
        - tox -e lint -e test -e codecov
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox
          - /c/Python36
          - ${TRAVIS_BUILD_DIR}/REAMDE.md

    - stage: release
      name: macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==3.0.0
      script:
        - tox -e release
      cache:
        directories:
          - ${HOME}/.pyenv_cache
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: release
      name: linux
      language: python
      python: "3.6"
      env:
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      install:
        - pip install tox==3.0.0
        - tox --notest -e release
      script:
        - tox -e release
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox

    - stage: release
      name: windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - CACHE_NAME=${TRAVIS_JOB_NAME}
      before_install: choco install python --version 3.6.7
      install:
        - pip install tox==3.0.0
        - tox --notest -e release
      script:
        - tox -e release
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/.tox
          - /c/Python36
          - ${TRAVIS_BUILD_DIR}/REAMDE.md

branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

