sudo: false
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TOX_ENV=py27
        - PYTHON=2.7.14
    - os: osx
      language: generic
      env:
        - TOX_ENV=py36
        - PYTHON=3.6.4


cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - ${HOME}/.pyenv
    - ${HOME}/.tox
    - /usr/local/Cellar/pyenv/1.2.4


install: |

  if [ ! -d ${HOME}/.pyenv/versions/${PYTHON} ]; then

    echo "[install] Installing pyenv..."
    brew upgrade pyenv
    echo "[install] Successfully installed pyenv"

    echo "Checking which pyenv version was installed"
    pyenv --version

    echo "[install] Initializing pyenv..."
    eval "$(pyenv init -)"
    echo "[install] Successfully initialized pyenv..."

    echo "[install] Installing python ${PYTHON} with pyenv..."
    # --enable-shared is needed for pyinstaller.
    env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install -s ${PYTHON}
    pyenv global ${PYTHON}
    echo "[install] Successfully installed python ${PYTHON} with pyenv..."

    echo "[install] Checking where python is"
    which python

    echo "[install] Checking python version"
    $(which python) --version

    echo "[install] Checking where pip is"
    which pip

    echo "[install] Finished installing and configuring python"

  fi

script:
  - tox -e ${TOX_ENV}
