sudo: false

stages:
  - integration
  - release


jobs:
  include:

    - stage: integration
      name: integration-py27-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=2.7.14
        - PYENV_VERSION=2.7.14
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==3.0.0
      script:
        - tox -e lint-py27 && tox -e test-py27 && tox -e codecov

    - stage: integration
      name: integration-py36-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==3.0.0
      script:
        - tox -e lint-py27 && tox -e test-py27 && tox -e codecov

    - stage: integration
      name: integration-py27-linux
      language: python
      python: "3.6"
      install:
        - pip install tox==3.0.0
      script:
        - tox -e lint-py36 && tox -e test-py36 && tox -e codecov

    - stage: integration
      name: integration-py36-linux
      language: python
      python: "3.6"
      install:
        - pip install tox==3.0.0
      script:
        - tox -e lint-py36 && tox -e test-py36 && tox -e codecov

    - stage: release
      name: release-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      install:
        - pip install tox==3.0.0
      script:
        - tox -e release

    - stage: release
      name: release-linux
      language: python
      python: "3.6"
      install:
        - pip install tox==3.0.0
      script:
        - tox -e release


#    - stage: ci
#      name: ci-py36
#      env:
#        - PYTHON=3.6.4
#        - PYENV_VERSION=3.6.4
#      script:
#        - tox -e lint-py36 && tox -e test-py36 && tox -e codecov
#
#    - stage: release
#      name: release-macos
#      env:
#        - PYTHON=3.6.4
#        - PYENV_VERSION=3.6.4
#      script:
#        - tox -e release
#
#    - stage: release
#      name: release-linux
#      env:
#        - PYTHON=3.6.4
#        - PYENV_VERSION=3.6.4
#      script:
#        - tox -e release


cache:
  directories:
    - ${HOME}/.pyenv_cache

branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

