sudo: false

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: test-py27
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=2.7.14
        - PYENV_VERSION=2.7.14
      script: tox -e test-py27
    - stage: test
      name: test-py36
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      script: tox -e test-py36
    - stage: test
      name: test-cross-distro
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      script: tox -e test-cross-distro
    - stage: release
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYTHON=3.6.4
        - PYENV_VERSION=3.6.4
      name: release
      script: tox -e release


branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

cache:
  directories:
    - ${HOME}/.pyenv_cache
    - ${TRAVIS_BUILD_DIR}/.tox

install:
  - pip install tox==3.0.0

before_install: |

  source setup-pyenv.sh
