matrix:
  include:
    - os: linux
      language: python
      python: "2.7"
    - os: osx
      language: generic


script:
  - ./ci/scripts/linux/ci.sh
after_success:
  - codecov
notifications:
    webhooks: https://www.travisbuddy.com/