sudo: false

stages:
  - ci
#  - release


matrix:

  include:

    - os: osx
      language: generic
      osx_image: xcode7.3
      before_install: source setup-pyenv.sh

    - language: python
      python: "2.7"

jobs:
  include:

    - stage: ci
      name: ci-py27
      env:
        - PYTHON=2.7.14
        - PYENV_VERSION=2.7.14
      install:
        - pip install tox==3.0.0
      script:
        - tox -e lint-py27 && tox -e test-py27 && tox -e codecov

#    - stage: ci
#      name: ci-py36
#      env:
#        - PYTHON=3.6.4
#        - PYENV_VERSION=3.6.4
#      script:
#        - tox -e lint-py36 && tox -e test-py36 && tox -e codecov
#
#    - stage: release
#      name: release-macos
#      env:
#        - PYTHON=3.6.4
#        - PYENV_VERSION=3.6.4
#      script:
#        - tox -e release
#
#    - stage: release
#      name: release-linux
#      env:
#        - PYTHON=3.6.4
#        - PYENV_VERSION=3.6.4
#      script:
#        - tox -e release


cache:
  directories:
    - ${HOME}/.pyenv_cache

branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

