sudo: false

stages:
  - integration
  - release

env:
  global:
    - CACHE_NAME=${TRAVIS_JOB_NAME}

_commands_provider:
  _test-unit: &_test-unit "py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m \"not cross_distro\" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir ."
  _test-cross-distro: &_test-cross-distro "py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m cross_distro -rs -c pytest.ini pyci/tests --rootdir ."
  _lint: &_lint "pylint --rcfile pylint.ini pyci"
  _release: &_release "pyci release --wheel-universal --binary-entrypoint pyci.spec"

jobs:
  include:

    - stage: integration
      name: py27-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=2.7.14
      before_install: source setup-pyenv.sh
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      before_script:
        - pylint --rcfile pylint.ini pyci
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m "not cross_distro" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f coverage.xml
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py36-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      before_script:
        - pylint --rcfile pylint.ini pyci
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m "not cross_distro" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f coverage.xml
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py27-linux
      language: python
      python: "2.7"
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      before_script:
        - *_lint
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m "not cross_distro" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f coverage.xml

    - stage: integration
      name: py36-linux
      language: python
      python: "3.6"
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      before_script:
        - pylint --rcfile pylint.ini pyci
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m "not cross_distro" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f coverage.xml

    - stage: integration
      name: binary-cross-distro-linux
      language: python
      python: "3.6"
      services:
        - docker
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m cross_distro -rs -c pytest.ini pyci/tests --rootdir .

    - stage: integration
      name: py27-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install:
        # https://ttcshelbyville.wordpress.com/2012/12/19/disable-remote-differential-compression-form-the-command-line/
        - powershell Disable-WindowsOptionalFeature -Online -FeatureName MSRDC-Infrastructure

        # https://travis-ci.community/t/yarn-network-troubles/333/7
        - powershell Set-MpPreference -DisableRealtimeMonitoring \$true
        - choco install python2
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      before_script:
        - pylint --rcfile pylint.ini pyci
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m "not cross_distro" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f coverage.xml

    - stage: integration
      name: py36-windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        # https://ttcshelbyville.wordpress.com/2012/12/19/disable-remote-differential-compression-form-the-command-line/
        - powershell Disable-WindowsOptionalFeature -Online -FeatureName MSRDC-Infrastructure

        # https://travis-ci.community/t/yarn-network-troubles/333/7
        - powershell Set-MpPreference -DisableRealtimeMonitoring \$true
        - choco install python --version 3.6.7
      install:
        - pip install -r test-requirements.txt
        - pip install -e .
      before_script:
        - pylint --rcfile pylint.ini pyci
      script:
        - py.test --junitxml=reports/test/pytest/junit.xml -s --durations=10 -v -m "not cross_distro" -rs -c pytest.ini  --cov-config=coverage.ini --cov=pyci pyci/tests --rootdir .
      after_success:
        - bash <(curl -s https://codecov.io/bash) -Z -f coverage.xml

    - stage: release
      name: macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      install:
        - pip install -e .
      script:
        - pyci release --wheel-universal --binary-entrypoint pyci.spec
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: release
      name: linux
      language: python
      python: "3.6"
      install:
        - pip install -e .
      script:
        - pyci release --wheel-universal --binary-entrypoint pyci.spec

    - stage: release
      name: windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        # https://ttcshelbyville.wordpress.com/2012/12/19/disable-remote-differential-compression-form-the-command-line/
        - powershell Disable-WindowsOptionalFeature -Online -FeatureName MSRDC-Infrastructure

        # https://travis-ci.community/t/yarn-network-troubles/333/7
        - powershell Set-MpPreference -DisableRealtimeMonitoring \$true
        - choco install python --version 3.6.7
      install:
        - pip install -e .
      script:
        - pyci release --wheel-universal --binary-entrypoint pyci.spec

branches:
  except:
    - master
    - /\d*\.\d*\.\d*/

