version: 2
jobs:
  python27:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install tox
          command: sudo pip install tox==3.0.0
      - restore_cache:
          keys:
            - tox-cache
      - save_cache:
          key: tox-cache
          paths:
            - .tox
      - run:
          name: run tox
          command: tox

workflows:
  version: 2
  python:
    jobs:
      - python27
