version: 2.1

commands:
  run-tox:
    description: Run a specific tox environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - tox-{{ checksum "test-requirements.txt" }}-{{ checksum "setup.py" }}
      - run:
          name: tox
          command: |
            sudo pip install tox==3.0.0
            tox -e ${CIRCLE_JOB}
      - save_cache:
          key: tox-{{ checksum "test-requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - .tox

jobs:
  lint-py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - run-tox
  lint-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run-tox
  test-py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - run-tox
      - store_test_results:
          path: reports/test
      - store_artifacts:
          path: reports/test
      - persist_to_workspace:
          root: reports/coverage
          paths:
            - coverage
  test-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run-tox
      - store_test_results:
          path: reports/test
      - store_artifacts:
          path: reports/test
      - persist_to_workspace:
          root: reports/coverage
          paths:
            - coverage
  codecov-py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: reports/coverage
      - run-tox
  codecov-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: reports/coverage
      - run-tox
  test-cross-distro:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - run-tox
  release:
    docker:
      - image: circleci/python:3.6
    steps:
      - run-tox


workflows:
  version: 2
  ci:
    jobs:
      - lint-py27:
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/
      - lint-py36:
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/
      - test-py27:
          requires:
            - lint-py27
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/
      - test-py36:
          requires:
            - lint-py36
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/
      - test-cross-distro:
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/
      - codecov-py27:
          requires:
            - test-py27
          filters:
            branches:
              ignore:
                - master
      - codecov-py36:
          requires:
            - test-py36
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/
                - /\d*\.\d*\.\d*/
      - release:
          requires:
            - codecov-py27
            - codecov-py36
            - test-cross-distro
          filters:
            branches:
              ignore:
                - master
                - /\d*\.\d*\.\d*/

