version: 2
jobs:
  pyton2.7.14:
    docker:
      - image: circleci/python:2.7.14
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: ci
          command: ./ci/scripts/linux/ci.sh