version: 2
jobs:
  python27:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install
          command: pip install tox==3.0.0
      - run:
          name: tox
          command: tox

workflows:
  version: 2
  python:
    jobs:
      - python27
